version: "3.3"

# Services describes services that will start:
services:
  # api is the container name for our API:
  api:
    # Build the dockerfile from the project root:
    build: "."
    # Expose the port 5000 and let compose manage it:
    ports:
      - "5000"
    # Always restart the container:
    restart: "always"
    # Connect the api to the common api.network bridge:
    networks:
      - "api.network"
    # Start replicas of the api image:
    deploy:
      replicas: 5
  # nginx containter:
  nginx:
    # Pull the latest nginx image:
    image: nginx:latest
    # Connect the conf file in the image to the one in the repo:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # Start only after the API containers are ready:
    depends_on:
      - api
    # Connect the port 80 to nginx:
    ports:
      - "80:80"
    # Connect the load balancer to the common network:
    networks:
      - "api.network"

# Declare a network to connect all apps:
networks:
  api.network:
